"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import acapy_client
from acapy_client.api.out_of_band_api import OutOfBandApi  # noqa: E501


class TestOutOfBandApi(unittest.TestCase):
    """OutOfBandApi unit test stubs"""

    def setUp(self):
        self.api = OutOfBandApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_out_of_band_create_invitation_post(self):
        """Test case for out_of_band_create_invitation_post

        Create a new connection invitation  # noqa: E501
        """
        pass

    def test_out_of_band_receive_invitation_post(self):
        """Test case for out_of_band_receive_invitation_post

        Receive a new connection invitation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
