"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.v10_presentation_exchange import V10PresentationExchange
globals()['V10PresentationExchange'] = V10PresentationExchange
from acapy_client.model.v10_presentation_exchange_list import V10PresentationExchangeList


class TestV10PresentationExchangeList(unittest.TestCase):
    """V10PresentationExchangeList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10PresentationExchangeList(self):
        """Test V10PresentationExchangeList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V10PresentationExchangeList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
