"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.menu_form_param import MenuFormParam
globals()['MenuFormParam'] = MenuFormParam
from acapy_client.model.menu_form import MenuForm


class TestMenuForm(unittest.TestCase):
    """MenuForm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMenuForm(self):
        """Test MenuForm"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MenuForm()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
