"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.v20_cred_attr_spec import V20CredAttrSpec
globals()['V20CredAttrSpec'] = V20CredAttrSpec
from acapy_client.model.v20_cred_preview import V20CredPreview


class TestV20CredPreview(unittest.TestCase):
    """V20CredPreview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20CredPreview(self):
        """Test V20CredPreview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20CredPreview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
