"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.attachment_def import AttachmentDef
globals()['AttachmentDef'] = AttachmentDef
from acapy_client.model.invitation_create_request import InvitationCreateRequest


class TestInvitationCreateRequest(unittest.TestCase):
    """InvitationCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvitationCreateRequest(self):
        """Test InvitationCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InvitationCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
