"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import acapy_client
from acapy_client.api.didcomm_resolver_api import DidcommResolverApi  # noqa: E501


class TestDidcommResolverApi(unittest.TestCase):
    """DidcommResolverApi unit test stubs"""

    def setUp(self):
        self.api = DidcommResolverApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_register_resolver_connection(self):
        """Test case for register_resolver_connection

        Register DIDcomm resolver.  # noqa: E501
        """
        pass

    def test_resolver_connection(self):
        """Test case for resolver_connection

        List DIDcomm resolvers.  # noqa: E501
        """
        pass

    def test_resolver_connection_0(self):
        """Test case for resolver_connection_0

        Fetch DIDComm Resolver details.  # noqa: E501
        """
        pass

    def test_resolver_update_conn_id_post(self):
        """Test case for resolver_update_conn_id_post

        Update DIDcomm resolvable methods.  # noqa: E501
        """
        pass

    def test_unset_resolver_connection(self):
        """Test case for unset_resolver_connection

        Remove an existing connection record.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
