"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.create_invitation_request import CreateInvitationRequest


class TestCreateInvitationRequest(unittest.TestCase):
    """CreateInvitationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateInvitationRequest(self):
        """Test CreateInvitationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateInvitationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
