"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.attach_decorator_data_jws_header import AttachDecoratorDataJWSHeader
globals()['AttachDecoratorDataJWSHeader'] = AttachDecoratorDataJWSHeader
from acapy_client.model.attach_decorator_data1_jws import AttachDecoratorData1JWS


class TestAttachDecoratorData1JWS(unittest.TestCase):
    """AttachDecoratorData1JWS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttachDecoratorData1JWS(self):
        """Test AttachDecoratorData1JWS"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttachDecoratorData1JWS()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
