"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.v20_pres_proposal_by_format import V20PresProposalByFormat
globals()['V20PresProposalByFormat'] = V20PresProposalByFormat
from acapy_client.model.v20_pres_proposal_request import V20PresProposalRequest


class TestV20PresProposalRequest(unittest.TestCase):
    """V20PresProposalRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20PresProposalRequest(self):
        """Test V20PresProposalRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20PresProposalRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
