"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import acapy_client
from acapy_client.api.did_exchange_api import DidExchangeApi  # noqa: E501


class TestDidExchangeApi(unittest.TestCase):
    """DidExchangeApi unit test stubs"""

    def setUp(self):
        self.api = DidExchangeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_didexchange_conn_id_accept_invitation_post(self):
        """Test case for didexchange_conn_id_accept_invitation_post

        Accept a stored connection invitation  # noqa: E501
        """
        pass

    def test_didexchange_conn_id_accept_request_post(self):
        """Test case for didexchange_conn_id_accept_request_post

        Accept a stored connection request  # noqa: E501
        """
        pass

    def test_didexchange_create_request_post(self):
        """Test case for didexchange_create_request_post

        Create request against public DID's implicit invitation  # noqa: E501
        """
        pass

    def test_didexchange_receive_request_post(self):
        """Test case for didexchange_receive_request_post

        Receive request against public DID's implicit invitation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
