"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.did_endpoint_with_type import DIDEndpointWithType


class TestDIDEndpointWithType(unittest.TestCase):
    """DIDEndpointWithType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDIDEndpointWithType(self):
        """Test DIDEndpointWithType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DIDEndpointWithType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
