"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.v20_pres_proposal_by_format import V20PresProposalByFormat


class TestV20PresProposalByFormat(unittest.TestCase):
    """V20PresProposalByFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20PresProposalByFormat(self):
        """Test V20PresProposalByFormat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20PresProposalByFormat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
