"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.menu_option import MenuOption
globals()['MenuOption'] = MenuOption
from acapy_client.model.menu_json import MenuJson


class TestMenuJson(unittest.TestCase):
    """MenuJson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMenuJson(self):
        """Test MenuJson"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MenuJson()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
