"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import acapy_client
from acapy_client.api.connection_api import ConnectionApi  # noqa: E501


class TestConnectionApi(unittest.TestCase):
    """ConnectionApi unit test stubs"""

    def setUp(self):
        self.api = ConnectionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_connections_conn_id_accept_invitation_post(self):
        """Test case for connections_conn_id_accept_invitation_post

        Accept a stored connection invitation  # noqa: E501
        """
        pass

    def test_connections_conn_id_accept_request_post(self):
        """Test case for connections_conn_id_accept_request_post

        Accept a stored connection request  # noqa: E501
        """
        pass

    def test_connections_conn_id_delete(self):
        """Test case for connections_conn_id_delete

        Remove an existing connection record  # noqa: E501
        """
        pass

    def test_connections_conn_id_endpoints_get(self):
        """Test case for connections_conn_id_endpoints_get

        Fetch connection remote endpoint  # noqa: E501
        """
        pass

    def test_connections_conn_id_establish_inbound_ref_id_post(self):
        """Test case for connections_conn_id_establish_inbound_ref_id_post

        Assign another connection as the inbound connection  # noqa: E501
        """
        pass

    def test_connections_conn_id_get(self):
        """Test case for connections_conn_id_get

        Fetch a single connection record  # noqa: E501
        """
        pass

    def test_connections_conn_id_metadata_get(self):
        """Test case for connections_conn_id_metadata_get

        Fetch connection metadata  # noqa: E501
        """
        pass

    def test_connections_conn_id_metadata_post(self):
        """Test case for connections_conn_id_metadata_post

        Set connection metadata  # noqa: E501
        """
        pass

    def test_connections_create_invitation_post(self):
        """Test case for connections_create_invitation_post

        Create a new connection invitation  # noqa: E501
        """
        pass

    def test_connections_create_static_post(self):
        """Test case for connections_create_static_post

        Create a new static connection  # noqa: E501
        """
        pass

    def test_connections_get(self):
        """Test case for connections_get

        Query agent-to-agent connections  # noqa: E501
        """
        pass

    def test_connections_receive_invitation_post(self):
        """Test case for connections_receive_invitation_post

        Receive a new connection invitation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
