"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.indy_pres_preview import IndyPresPreview
globals()['IndyPresPreview'] = IndyPresPreview
from acapy_client.model.v10_presentation_proposal_request import V10PresentationProposalRequest


class TestV10PresentationProposalRequest(unittest.TestCase):
    """V10PresentationProposalRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10PresentationProposalRequest(self):
        """Test V10PresentationProposalRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V10PresentationProposalRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
