"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.rev_reg_update_tails_file_uri import RevRegUpdateTailsFileUri


class TestRevRegUpdateTailsFileUri(unittest.TestCase):
    """RevRegUpdateTailsFileUri unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRevRegUpdateTailsFileUri(self):
        """Test RevRegUpdateTailsFileUri"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RevRegUpdateTailsFileUri()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
