"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import acapy_client
from acapy_client.api.present_proof_v2_0_api import PresentProofV20Api  # noqa: E501


class TestPresentProofV20Api(unittest.TestCase):
    """PresentProofV20Api unit test stubs"""

    def setUp(self):
        self.api = PresentProofV20Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_present_proof20_create_request_post(self):
        """Test case for present_proof20_create_request_post

        Creates a presentation request not bound to any proposal or connection  # noqa: E501
        """
        pass

    def test_present_proof20_records_get(self):
        """Test case for present_proof20_records_get

        Fetch all present-proof exchange records  # noqa: E501
        """
        pass

    def test_present_proof20_records_pres_ex_id_credentials_get(self):
        """Test case for present_proof20_records_pres_ex_id_credentials_get

        Fetch credentials from wallet for presentation request  # noqa: E501
        """
        pass

    def test_present_proof20_records_pres_ex_id_delete(self):
        """Test case for present_proof20_records_pres_ex_id_delete

        Remove an existing presentation exchange record  # noqa: E501
        """
        pass

    def test_present_proof20_records_pres_ex_id_get(self):
        """Test case for present_proof20_records_pres_ex_id_get

        Fetch a single presentation exchange record  # noqa: E501
        """
        pass

    def test_present_proof20_records_pres_ex_id_problem_report_post(self):
        """Test case for present_proof20_records_pres_ex_id_problem_report_post

        Send a problem report for presentation exchange  # noqa: E501
        """
        pass

    def test_present_proof20_records_pres_ex_id_send_presentation_post(self):
        """Test case for present_proof20_records_pres_ex_id_send_presentation_post

        Sends a proof presentation  # noqa: E501
        """
        pass

    def test_present_proof20_records_pres_ex_id_send_request_post(self):
        """Test case for present_proof20_records_pres_ex_id_send_request_post

        Sends a presentation request in reference to a proposal  # noqa: E501
        """
        pass

    def test_present_proof20_records_pres_ex_id_verify_presentation_post(self):
        """Test case for present_proof20_records_pres_ex_id_verify_presentation_post

        Verify a received presentation  # noqa: E501
        """
        pass

    def test_present_proof20_send_proposal_post(self):
        """Test case for present_proof20_send_proposal_post

        Sends a presentation proposal  # noqa: E501
        """
        pass

    def test_present_proof20_send_request_post(self):
        """Test case for present_proof20_send_request_post

        Sends a free presentation request not bound to any proposal  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
