"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import acapy_client
from acapy_client.api.mediation_api import MediationApi  # noqa: E501


class TestMediationApi(unittest.TestCase):
    """MediationApi unit test stubs"""

    def setUp(self):
        self.api = MediationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mediation_default_mediator_delete(self):
        """Test case for mediation_default_mediator_delete

        Clear default mediator  # noqa: E501
        """
        pass

    def test_mediation_default_mediator_get(self):
        """Test case for mediation_default_mediator_get

        Get default mediator  # noqa: E501
        """
        pass

    def test_mediation_keylists_get(self):
        """Test case for mediation_keylists_get

        Retrieve keylists by connection or role  # noqa: E501
        """
        pass

    def test_mediation_keylists_mediation_id_send_keylist_query_post(self):
        """Test case for mediation_keylists_mediation_id_send_keylist_query_post

        Send keylist query to mediator  # noqa: E501
        """
        pass

    def test_mediation_keylists_mediation_id_send_keylist_update_post(self):
        """Test case for mediation_keylists_mediation_id_send_keylist_update_post

        Send keylist update to mediator  # noqa: E501
        """
        pass

    def test_mediation_mediation_id_default_mediator_put(self):
        """Test case for mediation_mediation_id_default_mediator_put

        Set default mediator  # noqa: E501
        """
        pass

    def test_mediation_request_conn_id_post(self):
        """Test case for mediation_request_conn_id_post

        Request mediation from connection  # noqa: E501
        """
        pass

    def test_mediation_requests_get(self):
        """Test case for mediation_requests_get

        Query mediation requests, returns list of all mediation records  # noqa: E501
        """
        pass

    def test_mediation_requests_mediation_id_delete(self):
        """Test case for mediation_requests_mediation_id_delete

        Delete mediation request by ID  # noqa: E501
        """
        pass

    def test_mediation_requests_mediation_id_deny_post(self):
        """Test case for mediation_requests_mediation_id_deny_post

        Deny a stored mediation request  # noqa: E501
        """
        pass

    def test_mediation_requests_mediation_id_get(self):
        """Test case for mediation_requests_mediation_id_get

        Retrieve mediation request record  # noqa: E501
        """
        pass

    def test_mediation_requests_mediation_id_grant_post(self):
        """Test case for mediation_requests_mediation_id_grant_post

        Grant received mediation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
