"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.get_did_verkey_response import GetDIDVerkeyResponse


class TestGetDIDVerkeyResponse(unittest.TestCase):
    """GetDIDVerkeyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetDIDVerkeyResponse(self):
        """Test GetDIDVerkeyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetDIDVerkeyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
