"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.v20_pres_problem_report_request import V20PresProblemReportRequest


class TestV20PresProblemReportRequest(unittest.TestCase):
    """V20PresProblemReportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20PresProblemReportRequest(self):
        """Test V20PresProblemReportRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20PresProblemReportRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
