"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.v20_pres_ex_record import V20PresExRecord
globals()['V20PresExRecord'] = V20PresExRecord
from acapy_client.model.v20_pres_ex_record_list import V20PresExRecordList


class TestV20PresExRecordList(unittest.TestCase):
    """V20PresExRecordList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20PresExRecordList(self):
        """Test V20PresExRecordList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20PresExRecordList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
