"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.v20_cred_ex_record_indy import V20CredExRecordIndy
from acapy_client.model.v20_cred_ex_record_ld_proof import V20CredExRecordLDProof
globals()['V20CredExRecordIndy'] = V20CredExRecordIndy
globals()['V20CredExRecordLDProof'] = V20CredExRecordLDProof
from acapy_client.model.v20_cred_ex_record_detail import V20CredExRecordDetail


class TestV20CredExRecordDetail(unittest.TestCase):
    """V20CredExRecordDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20CredExRecordDetail(self):
        """Test V20CredExRecordDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20CredExRecordDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
