"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import acapy_client
from acapy_client.api.server_api import ServerApi  # noqa: E501


class TestServerApi(unittest.TestCase):
    """ServerApi unit test stubs"""

    def setUp(self):
        self.api = ServerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_features_get(self):
        """Test case for features_get

        Query supported features  # noqa: E501
        """
        pass

    def test_plugins_get(self):
        """Test case for plugins_get

        Fetch the list of loaded plugins  # noqa: E501
        """
        pass

    def test_shutdown_get(self):
        """Test case for shutdown_get

        Shut down server  # noqa: E501
        """
        pass

    def test_status_config_get(self):
        """Test case for status_config_get

        Fetch the server configuration  # noqa: E501
        """
        pass

    def test_status_get(self):
        """Test case for status_get

        Fetch the server status  # noqa: E501
        """
        pass

    def test_status_live_get(self):
        """Test case for status_live_get

        Liveliness check  # noqa: E501
        """
        pass

    def test_status_ready_get(self):
        """Test case for status_ready_get

        Readiness check  # noqa: E501
        """
        pass

    def test_status_reset_post(self):
        """Test case for status_reset_post

        Reset statistics  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
