"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.v10_credential_store_request import V10CredentialStoreRequest


class TestV10CredentialStoreRequest(unittest.TestCase):
    """V10CredentialStoreRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10CredentialStoreRequest(self):
        """Test V10CredentialStoreRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V10CredentialStoreRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
