"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.w3_c_credentials_list_request import W3CCredentialsListRequest


class TestW3CCredentialsListRequest(unittest.TestCase):
    """W3CCredentialsListRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testW3CCredentialsListRequest(self):
        """Test W3CCredentialsListRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = W3CCredentialsListRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
