"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.attach_decorator import AttachDecorator
from acapy_client.model.service import Service
globals()['AttachDecorator'] = AttachDecorator
globals()['Service'] = Service
from acapy_client.model.invitation_receive_request import InvitationReceiveRequest


class TestInvitationReceiveRequest(unittest.TestCase):
    """InvitationReceiveRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvitationReceiveRequest(self):
        """Test InvitationReceiveRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InvitationReceiveRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
