"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import acapy_client
from acapy_client.api.ledger_api import LedgerApi  # noqa: E501


class TestLedgerApi(unittest.TestCase):
    """LedgerApi unit test stubs"""

    def setUp(self):
        self.api = LedgerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ledger_did_endpoint_get(self):
        """Test case for ledger_did_endpoint_get

        Get the endpoint for a DID from the ledger.  # noqa: E501
        """
        pass

    def test_ledger_did_verkey_get(self):
        """Test case for ledger_did_verkey_get

        Get the verkey for a DID from the ledger.  # noqa: E501
        """
        pass

    def test_ledger_get_nym_role_get(self):
        """Test case for ledger_get_nym_role_get

        Get the role from the NYM registration of a public DID.  # noqa: E501
        """
        pass

    def test_ledger_register_nym_post(self):
        """Test case for ledger_register_nym_post

        Send a NYM registration to the ledger.  # noqa: E501
        """
        pass

    def test_ledger_rotate_public_did_keypair_patch(self):
        """Test case for ledger_rotate_public_did_keypair_patch

        Rotate key pair for public DID.  # noqa: E501
        """
        pass

    def test_ledger_taa_accept_post(self):
        """Test case for ledger_taa_accept_post

        Accept the transaction author agreement  # noqa: E501
        """
        pass

    def test_ledger_taa_get(self):
        """Test case for ledger_taa_get

        Fetch the current transaction author agreement, if any  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
