"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.v20_cred_issue_problem_report_request import V20CredIssueProblemReportRequest


class TestV20CredIssueProblemReportRequest(unittest.TestCase):
    """V20CredIssueProblemReportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20CredIssueProblemReportRequest(self):
        """Test V20CredIssueProblemReportRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20CredIssueProblemReportRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
