"""
    Aries Cloud Agent + didcomm_resolver Plugin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.6.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import acapy_client
from acapy_client.model.attach_decorator_data1_jws import AttachDecoratorData1JWS
from acapy_client.model.attach_decorator_data_jws_header import AttachDecoratorDataJWSHeader
globals()['AttachDecoratorData1JWS'] = AttachDecoratorData1JWS
globals()['AttachDecoratorDataJWSHeader'] = AttachDecoratorDataJWSHeader
from acapy_client.model.attach_decorator_data_jws import AttachDecoratorDataJWS


class TestAttachDecoratorDataJWS(unittest.TestCase):
    """AttachDecoratorDataJWS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttachDecoratorDataJWS(self):
        """Test AttachDecoratorDataJWS"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttachDecoratorDataJWS()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
