FROM python:3.6-alpine

WORKDIR /usr/src/app/

COPY run_tests.sh run_tests.sh
COPY test_didcomm_resolver.py test_didcomm_resolver.py
COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# Add docker-compose-wait tool -------------------
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait wait
RUN chmod +x wait

ENTRYPOINT ["./run_tests.sh"]
CMD ["-v"]
