FROM python:3.8-slim-buster

WORKDIR /home

COPY test-runner-requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# Add docker-compose-wait tool -------------------
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

RUN ["pytest", "-v", "--junitxml=reports/result.xml"]
# CMD tail -f /dev/null --------------- use this to keep container running to copy reports