name: Upload Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.6
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - name: Sanity check (run tests)
        run: |
          poetry run pytest
      - name: Build package
        run: |
          poetry build
      - name: Publish package
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{secrets.pypi_upload}}
        run: |
          poetry publish
